spring:
  application:
    name: course-service

  datasource:
    url: jdbc:postgresql://localhost:5432/coursedb
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true

info:
  app:
    name: COURSE SERVICE
    description: this is COURSE SERVICE
    version: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
